### ISSUE TITLE
Cant access currentIndex and onTap

### ISSUE THREAD

**Issue by ghost** [EdsonOnildoJR/scroll_bottom_navigation_bar#4]
Would be nice if the example showed exactly how to retrieve the current index and onTap, since the original bottom navigation bar provides this feature, I am currently struggling to make this work for me, the scrolling works but how do I use on tap to change screens.

**Comment by xJon** [comment]
You can just fork the project and add them yourself, that is what I did.

**Comment by edsonbonfim** [comment]
I have little time at the moment, but pull requests are welcome.

**Comment by edsonbonfim** [comment]
controller.bottomNavigationBar.tabNotifier is a ValueNotifier<int> that listen the tab changes. You can listen this instead use onTap. You can too add a onTap on ScrollBottomNavigationBar and attach this function to tabListener internaly.
